language: node_js
node_js: 
- "8.11.1"
before_install:
- npm install -g mocha
- npm install 
script: 
- npm test
branches:
- only
- develop
directories:
  - node_modules
after_script:
  - npm install -g codeclimate-test-reporter
  - codeclimate-test-reporter < coverage/lcov.info
after_success:
- npm run coveralls